export const realifeMarketplaceProtectedEscrow1155Abi = [
  {
    type: "function",
    name: "allowedNft",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "feeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint96" }],
  },
  {
    type: "function",
    name: "treasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "nextListingId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextPurchaseId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },

  {
    type: "function",
    name: "listings",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "seller", type: "address" },
      { name: "nft", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "pricePerUnitWei", type: "uint256" },
      { name: "amountTotal", type: "uint256" },
      { name: "amountRemaining", type: "uint256" },
      { name: "fulfillmentType", type: "uint8" },
      { name: "status", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "purchases",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [
      { name: "listingId", type: "uint256" },
      { name: "seller", type: "address" },
      { name: "buyer", type: "address" },
      { name: "nft", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "pricePerUnitWei", type: "uint256" },
      { name: "totalPriceWei", type: "uint256" },
      { name: "fulfillmentType", type: "uint8" },
      { name: "status", type: "uint8" },
      { name: "buyerConfirmed", type: "bool" },
      { name: "fundedAt", type: "uint64" },
      { name: "refundRequestedAt", type: "uint64" },
      { name: "nftReturnedAt", type: "uint64" },
      { name: "resolvedAt", type: "uint64" },
    ],
  },

  // actions
  {
    type: "function",
    name: "list1155",
    stateMutability: "nonpayable",
    inputs: [
      { name: "nft", type: "address" },
      { name: "tokenId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "pricePerUnitWei", type: "uint256" },
      { name: "fulfillmentType", type: "uint8" },
    ],
    outputs: [{ name: "listingId", type: "uint256" }],
  },
  {
    type: "function",
    name: "cancel",
    stateMutability: "nonpayable",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "buy",
    stateMutability: "payable",
    inputs: [
      { name: "listingId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "purchaseId", type: "uint256" }],
  },
  {
    type: "function",
    name: "buyerConfirm",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "buyerConfirmAndRelease",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "requestRefund",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "requestRefundAndReturnNft",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "returnPurchaseNft",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "releasePurchase",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "rejectRefundRequest",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "refundPurchase",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "rejectRefundAndRestoreBuyer",
    stateMutability: "nonpayable",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setAllowedNft",
    stateMutability: "nonpayable",
    inputs: [
      { name: "nft", type: "address" },
      { name: "allowed", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setTreasury",
    stateMutability: "nonpayable",
    inputs: [{ name: "t", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFeeBps",
    stateMutability: "nonpayable",
    inputs: [{ name: "bps", type: "uint96" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getListing",
    stateMutability: "view",
    inputs: [{ name: "listingId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "seller", type: "address" },
          { name: "nft", type: "address" },
          { name: "tokenId", type: "uint256" },
          { name: "pricePerUnitWei", type: "uint256" },
          { name: "amountTotal", type: "uint256" },
          { name: "amountRemaining", type: "uint256" },
          { name: "fulfillmentType", type: "uint8" },
          { name: "status", type: "uint8" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getPurchase",
    stateMutability: "view",
    inputs: [{ name: "purchaseId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "listingId", type: "uint256" },
          { name: "seller", type: "address" },
          { name: "buyer", type: "address" },
          { name: "nft", type: "address" },
          { name: "tokenId", type: "uint256" },
          { name: "amount", type: "uint256" },
          { name: "pricePerUnitWei", type: "uint256" },
          { name: "totalPriceWei", type: "uint256" },
          { name: "fulfillmentType", type: "uint8" },
          { name: "status", type: "uint8" },
          { name: "buyerConfirmed", type: "bool" },
          { name: "fundedAt", type: "uint64" },
          { name: "refundRequestedAt", type: "uint64" },
          { name: "nftReturnedAt", type: "uint64" },
          { name: "resolvedAt", type: "uint64" },
        ],
      },
    ],
  },

  // events
  {
    type: "event",
    name: "AllowedNftSet",
    anonymous: false,
    inputs: [
      { indexed: true, name: "nft", type: "address" },
      { indexed: false, name: "allowed", type: "bool" },
    ],
  },
  {
    type: "event",
    name: "TreasurySet",
    anonymous: false,
    inputs: [{ indexed: true, name: "treasury", type: "address" }],
  },
  {
    type: "event",
    name: "FeeBpsSet",
    anonymous: false,
    inputs: [{ indexed: false, name: "feeBps", type: "uint96" }],
  },
  {
    type: "event",
    name: "Listed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: true, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "pricePerUnitWei", type: "uint256" },
      { indexed: false, name: "fulfillmentType", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "Cancelled",
    anonymous: false,
    inputs: [
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: true, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amountReturned", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "PurchaseFunded",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: false, name: "buyer", type: "address" },
      { indexed: false, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "pricePerUnitWei", type: "uint256" },
      { indexed: false, name: "totalPriceWei", type: "uint256" },
      { indexed: false, name: "fulfillmentType", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "BuyerConfirmed",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
    ],
  },
  {
    type: "event",
    name: "RefundRequested",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
    ],
  },
  {
    type: "event",
    name: "PurchaseNftReturned",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: false, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "RefundRequestRejected",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
    ],
  },
  {
    type: "event",
    name: "PurchaseReleased",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: false, name: "buyer", type: "address" },
      { indexed: false, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "totalPriceWei", type: "uint256" },
      { indexed: false, name: "feeWei", type: "uint256" },
      { indexed: false, name: "sellerAmountWei", type: "uint256" },
      { indexed: false, name: "fulfillmentType", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "PurchaseRefunded",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "seller", type: "address" },
      { indexed: false, name: "buyer", type: "address" },
      { indexed: false, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "totalPriceWei", type: "uint256" },
      { indexed: false, name: "fulfillmentType", type: "uint8" },
    ],
  },
  {
    type: "event",
    name: "RefundRejectedAndNftRestored",
    anonymous: false,
    inputs: [
      { indexed: true, name: "purchaseId", type: "uint256" },
      { indexed: true, name: "listingId", type: "uint256" },
      { indexed: true, name: "buyer", type: "address" },
      { indexed: false, name: "nft", type: "address" },
      { indexed: false, name: "tokenId", type: "uint256" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
] as const;